name: Run One-Time Processing Script

on:
  workflow_dispatch:

jobs:
  run-one-time-processing:
    name: Execute one_time_processing.py
    runs-on: self-hosted

    env:
      SQL_SERVER: ${{ secrets.SQL_SERVER }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run one_time_processing.py with Conda and environment variables
        shell: cmd
        run: |
          CALL "C:\Users\papai\anaconda3\Scripts\activate.bat" RetailPulse_DW && python ./one_time_processing.py

      - name: Upload generated products CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-products-data
          path: datalake/raw_products_*.csv
